name: Debug
on:
  workflow_dispatch:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'# matches every branch
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
      branch:
        description: 'Define branch name'
        required: true
        default: 'main'
jobs:
  debug:
    name: Debugging job
    runs-on: ubuntu-latest
    env:
      CM_REGISTRY: ${{ secrets.CM_REGISTRY }}
    steps:
      - name: Test environment variable
        run: |
          echo ${{ env.CM_REGISTRY }}

      # https://github.com/mxschmitt/action-tmate?tab=readme-ov-file#manually-triggered-debug Info to activate
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
