name: Debug
on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
      branch:
        description: 'Define branch name'
        required: true
        default: 'main'
jobs:
  debug:
    name: Debugging job
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      REGISTRY_HOST: ${{ vars.CM_REGISTRY }}
      REGISTRY_USERNAME: ${{ vars.REGISTRY_USERNAME }}
    runs-on: ubuntu-latest
    steps:
      - name: Load secrets from 1pass
        uses: 1password/load-secrets-action@v2
        with:
          # Export loaded secrets as environment variables
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          REPOSITORY_OWNER: "op://Homelab/Github Actions -Helmseum/username"
          GITHUB_REPOSITORY: "op://Homelab/Github Actions -Helmseum/repo"

      - name: Print masked secret
        run: |
          echo "REPOSITORY_OWNER: $REPOSITORY_OWNER"
          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"

      - name: Test environment variable
        run: |
          echo REGISTRY_HOST: $REGISTRY_HOST
          echo secret: ${{ secrets.TEST }}

      # https://github.com/mxschmitt/action-tmate?tab=readme-ov-file#manually-triggered-debug Info to activate
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
