name: Debug
on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
      branch:
        description: 'Define branch name'
        required: true
        default: 'main'
jobs:
  debug:
    name: Debugging job
    runs-on: ubuntu-latest
    steps:
      - name: Test environment variable
        run: |
          echo env: "${{ vars.TEST_VARIABLE }}"
          echo secret: ${{ secrets.TEST }}

      # https://github.com/mxschmitt/action-tmate?tab=readme-ov-file#manually-triggered-debug Info to activate
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
